apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: rakshithshenoy/payments
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "ticketing"
            - name: JWT_KEY
              value: asdf
            - name: MONGO_URI
              value: "mongodb://payments-mongo-srv:27017/payments"
            - name: STRIPE_KEY
              value: "sk_test_51Mzh1SSCytVSzppJuMRu4uAUz0wo2njVRonsq5cjKY7PDytcchYweHLk54pfktSHRaSEMTktWTI9v4JJe1haKr8000ExHhwUGi"
          resources:
            limits:
              memory: "400Mi"
              cpu: "150m"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - port: 3000
      targetPort: 3000
